v1.91 several fixes
* Make WorldGuardHook cause NoClassDefFoundError only one times.
* Add two reload events so that we can hook into SkillAPI better.